### ISSUE TITLE
Native support for holes in line charts

### ISSUE THREAD

**Issue by gionkunz** [oliveraustria/chartist-plugin-missing-data#3]
Hi @oliveraustria 

I just wanted to let you know that with the next release of Chartist 0.8 which will go public presumably after this weekend, holes in line charts are supported natively.

Cheers
Gion

**Comment by gionkunz** [comment]
And I wanted to say thanks again for providing this plugin for the users so far!

**Comment by oliveraustria** [comment]
Great!! Thanks for providing this feature in the core and the knowledge I learned by developing the plugin (involving your hints :)

Best wishes,
Oliver
